
name: Continous Integration and Deployement


on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: Set up .Net
        uses: actions/setup-dotnet@v1.0.0
        with:
           dotnet-version: 6.0.201


      - name: Restore dependencies
        run: dotnet restore

      - name: build app
        run: dotnet build -c Release --no-restore
        


